version: '3.9'

services:
  django:
    build:
      context: /webapp
    restart: always
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/home/meta
    ports:
      - 8000:8000
    command: python3 ./src/manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "meta_postgres_db01"
      POSTGRES_USER: "void"
      POSTGRES_PASSWORD: "hotel"
    container_name: postgres
    volumes:
      - meta_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  meta_postgres:  
