# Generated by Django 4.2.1 on 2023-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelhistory',
            name='linked_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['supplier'], name='api_hotel_supplie_d49be3_idx'),
        ),
    ]
