# Generated by Django 4.2.1 on 2023-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hotelhistory_linked_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotel',
            name='api_hotel_supplie_d49be3_idx',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='supplier',
            new_name='meta_hotel',
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['meta_hotel'], name='api_hotel_meta_ho_b64780_idx'),
        ),
    ]
